### ISSUE TITLE
python 3.14 and lz4

### ISSUE THREAD

**Issue by jcfuentes** [danielhrisca/asammdf#1249]
hi, I had this very weird error while upgrading to python 3.14:

```shell
ImportError: cannot import name '_compression' from partially initialized module 'lz4.frame' (most likely due to a circular import) (C:\PrivTools\Python314\Lib\site-packages\lz4\frame\__init__.py)
```

The same code works fine with python 3.13.

After debugging for a while, I had to patch the file lz4/frame/__init__.py:

```python
__doc__ = _doc


import compression._common._streams as _compression  # Python 3.14


BLOCKSIZE_DEFAULT = _BLOCKSIZE_DEFAULT
```

This solved the problem and I can continue to use this great library and with python 3.14 I got a 10% speed up on my project.

Hope it helps other people having the same issue (the issue is related to lz4, not asammdf).

**Comment by jcfuentes** [comment]
issue fixed yesterday in lz4:
https://github.com/python-lz4/python-lz4/issues/308

**Comment by jcfuentes** [comment]
I will close the issue since the wheels for lz4 compatible for python 3.14 are already available. (lz4 4.4.5)
