### ISSUE TITLE
Exception during file Opening

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#248]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '
'(Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.10.3'
# Code 

  ## MDF version
4.10

  ## Code snippet
    def __del__(self):
        self.close()
  
  ## Traceback
 File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.13.1-py3.7.egg\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.13.1-py3.7.egg\asammdf\blocks\mdf_v4.py", line 321, in __init__
    self._read(mapped=False)
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.13.1-py3.7.egg\asammdf\blocks\mdf_v4.py", line 518, in _read
    self._read_channels(ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped)
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.13.1-py3.7.egg\asammdf\blocks\mdf_v4.py", line 879, in _read_channels
    mapped=mapped,
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.13.1-py3.7.egg\asammdf\blocks\v4_blocks.py", line 709, in __init__
    params[10] = 1
TypeError: 'tuple' object does not support item assignment
Exception ignored in: <function MDF.__del__ at 0x09B21ED0>
Traceback (most recent call last):
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.13.1-py3.7.egg\asammdf\mdf.py", line 164, in __del__
    self.close()
AttributeError: 'MDF' object has no attribute 'close'
  
# Description
When opening a MF4 File i get the Error shown above.
Despite my changes mentioned here, 
https://github.com/danielhrisca/asammdf/issues/236
it worked with asammdf 5.10.3

**Comment by danielhrisca** [comment]
Hello @mikesmitti ,

this should be fixed in the development branch.

I will also look into the dbc issue

**Comment by mikesmitti** [comment]
Hello @danielhrisca ,
I get this error with versions 5-13-1, 5-13-2, 5-13-6 and 5-13-9 today.
I repeatedly corresponds to the topic in https://github.com/danielhrisca/asammdf/issues/236
Every time, i fix it the way mentioned, it works again.

Best regards,
Mike

**Comment by danielhrisca** [comment]
Hello Mike,

please check the development branch
