### ISSUE TITLE
Exception in numeric mode

### ISSUE THREAD

**Issue by eblis** [danielhrisca/asammdf#816]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 '
 'bit (AMD64)]')
'numpy=1.23.5'
'asammdf=7.2.0'
```

  ## MDF version
4.10

  ## Traceback
```python
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\file.py", line 1566, in _create_window
    self.add_window((window_type, signals))
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 1043, in add_window
    return self._add_numeric_window(names)
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 1999, in _add_numeric_window
    numeric = Numeric([], parent=self, mode="offline")
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\numeric.py", line 1170, in __init__
    self.channels = NumericViewer(backend)
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\numeric.py", line 982, in __init__
    self.dataView = TableView(parent=self)
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\numeric.py", line 630, in __init__
    self.setDragDropMode(self.InternalMove)

<class 'AttributeError'>: 'TableView' object has no attribute 'InternalMove'
```
  
# Description

Trying to view some signals in `Numeric` mode with the GUI

# Dependencies
```
[tool.poetry.group.dev.dependencies]
pyqtgraph = "^0.13.1"
pyside6 = "^6.4.2"
natsort = "^8.2.0"
psutil = "^5.9.4"
pyqtlet2 = "^0.9.2"
```

**Comment by danielhrisca** [comment]
Try de development branch the the two issues

**Comment by eblis** [comment]
Still happens in 7.3.1

**Comment by danielhrisca** [comment]
please try `PySide==6.3.1`

**Comment by eblis** [comment]
Works with `PySide6==6.3.1`.
```
asammdf 7.3.1 ASAM MDF measurement data file parser
├── canmatrix >=0.8
│   ├── attrs >=19.2.0
│   ├── click *
│   │   └── colorama *
│   ├── future *
│   ├── lxml *
│   └── six *
├── isal *
├── lz4 *
├── numexpr *
│   └── numpy >=1.13.3
├── numpy >=1.23.0
├── pandas *
│   ├── numpy >=1.20.3
│   ├── numpy >=1.21.0 (circular dependency aborted here)
│   ├── python-dateutil >=2.8.1
│   │   └── six >=1.5
│   └── pytz >=2020.1
├── python-dateutil *
│   └── six >=1.5
└── typing-extensions *
matplotlib 3.6.3 Python plotting package
├── contourpy >=1.0.1
│   └── numpy >=1.16
├── cycler >=0.10
├── fonttools >=4.22.0
├── kiwisolver >=1.0.1
├── numpy >=1.19
├── packaging >=20.0
├── pillow >=6.2.0
├── pyparsing >=2.2.1
└── python-dateutil >=2.7
    └── six >=1.5
pyside6 6.3.1 Python bindings for the Qt cross-platform application and UI framework
├── pyside6-addons 6.3.1
│   ├── pyside6-essentials 6.3.1
│   │   └── shiboken6 6.3.1
│   └── shiboken6 6.3.1 (circular dependency aborted here)
├── pyside6-essentials 6.3.1
│   └── shiboken6 6.3.1
└── shiboken6 6.3.1
```
