### ISSUE TITLE
AttributeError while running v5.20.0

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#353]
Python 3.6.4
asammdf=5.20.0

Hello Daniel,
I installed the latest asammdf Version today and encountered the error above when running this code. For the same file it was working well with version 5.19.16.

` with MDF(file,remove_source_from_channel_names=True, use_display_names=True) as mdf_file:
df = mdf_file.to_dataframe(Labels.name.tolist(),time_from_zero=False) `

'NoneType' object has no attribute 'split'
<class 'AttributeError'>

'NoneType' object has no attribute 'split'
Exception ignored in: <bound method MDF.__del__ of <asammdf.mdf.MDF object at 0x000001BDA6586160>>
Traceback (most recent call last):
  File "C:\..\Python\py36_4\lib\site-packages\asammdf\mdf.py", line 162, in __del__
    self.close()
AttributeError: 'MDF' object has no attribute 'close'

BR
Lama

**Comment by danielhrisca** [comment]
Please share the full error traceback mesaage

**Comment by Lama09** [comment]
Sorry there is not more than this.

'NoneType' object has no attribute 'split'
<class 'AttributeError'>

Exception ignored in: <bound method MDF.__del__ of <asammdf.mdf.MDF object at 0x00000235C28E0CF8>>
Traceback (most recent call last):
  File "C:\..\Python\py36_4\lib\site-packages\asammdf\mdf.py", line 162, in __del__
    self.close()
AttributeError: 'MDF' object has no attribute 'close'

**Comment by Lama09** [comment]
I also did a comment to this closed issue.
https://github.com/danielhrisca/asammdf/issues/352

**Comment by danielhrisca** [comment]
Please try the development branch code
